version: '3.8'

services:
  # 面倒なので、nginxは使わない

  # reverse-proxy:
  #   image: nginx:latest
  #   container_name: nginx_container_turbotest
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./packages/nginx-config/nginx.conf:/etc/nginx/nginx.conf
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
