// app配下にlayout.tsxを配置すると、
// 勝手にこれにラップされてルーティングされたページが返ってくる
// このファイルは必須

// @をつけたディレクトリ(これはルーティングされない)を利用できる
// default.tsxを配置しないと直接のアクセスに404が出る

import './globals.css';
import { Inter } from 'next/font/google';
import { clientEnv } from '@/constants';
import { CounterProvider } from '@/context/counter-provider';
import AppProvider from '@/providers/app';

// フォントの設定
const intr = Inter({ subsets: ['latin'] });

// headタグに入れるメタデータはmetadataに入れて設定できる
// これはpage.tsxでも設定できる
export const metadata = {
  title: {
    default: 'Create Next App',
    template: `%s | Next App`, // このようにすると全てのページのtitleにNext Appが付与される
  },
  description: 'Generated by create next app',
  // https://zenn.dev/temasaguru/articles/641a10cd5af02a
  metadataBase: new URL(clientEnv.NEXT_PUBLIC_HOST_URL),
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={intr.className}>
        <AppProvider>
          <CounterProvider>{children}</CounterProvider>
        </AppProvider>
      </body>
    </html>
  );
}
