---
name: バグ報告
about: プロジェクトのバグを報告するためのテンプレート
title: ''
labels: 'bug'
assignees: ''

---

**バグの説明**
バグに関する明確で簡潔な説明をお願いします。

**再現手順**
バグを再現するための手順:
1. '...'に移動
2. '....'をクリック
3. '....'をスクロールダウン
4. エラーが見える

**期待する振る舞い**
バグがなかった場合の、期待する振る舞いを明確にお知らせください。

**スクリーンショット**
可能であれば、問題の説明に役立つスクリーンショットを添付してください。

**デスクトップ (以下の情報を記入してください):**
 - OS: [例: iOS]
 - ブラウザ [例: chrome, safari]
 - バージョン [例: 22]

**スマートフォン (以下の情報を記入してください):**
 - デバイス: [例: iPhone6]
 - OS: [例: iOS8.1]
 - ブラウザ [例: stock browser, safari]
 - バージョン [例: 22]

**追加の情報**
バグに関するその他の情報があればこちらに追加してください。
